### ISSUE TITLE
`/admin/autocomplete/create` can throw 500 errors

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/pressfreedomtracker.us#1483]
Traceback from 2022-08-26:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "incident_charge_title_key"
DETAIL:  Key (title)=(penalties for political advertising) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtailautocomplete/views.py", line 109, in create
    instance = method(value)
  File "/django/incident/models/items.py", line 94, in autocomplete_create
    return kls.objects.create(title=value)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/modelcluster/models.py", line 201, in save
    super().save(update_fields=real_update_fields, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "incident_charge_title_key"
DETAIL:  Key (title)=(penalties for political advertising) already exists.
```

**Comment by harrislapiroff** [comment]
It's not clear if this one has been fixed in the course of autocomplete development in the past year or now. Someone should investigate.

**Comment by chigby** [comment]
Version 0.11.0 of wagtail-autocomplete (the latest) supports a more graceful handling of `ValidationError`s raised by the `autocomplete_create` method. Right now, according to the traceback in this issue, the `autocomplete_create` method is raising an `IntegrityError` that's not being handled at all. We can update our `autocomplete_create` methods to make sure the new object is valid before trying to save it, and raise a validation error otherwise, using some fairly straightforward additions as demonstrated in the wagtail-autocomplete docs:

https://github.com/wagtail/wagtail-autocomplete/blob/0cfc28d04acd58dc3b48d976eb4c7a1d43e6f68d/wagtailautocomplete/tests/testapp/models.py#L16-L21:

```python
    @classmethod
    def autocomplete_create(kls: type, value: str):
        instance = kls(title=value)
        instance.full_clean()
        instance.save()
        return instance
```

If we do this, similar situations to the one that triggered the error in this issue should result in 400s with appropriate error messages to the client. See https://github.com/wagtail/wagtail-autocomplete/pull/160 for more information.

**Comment by redshiftzero** [comment]
We hit a similar error again in the last couple of days in production when someone was using autocomplete for filling in the State field and selected "Create New":

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "incident_state_name_key"
DETAIL:  Key (name)=(Maryland) already exists.
```
