### ISSUE TITLE
Error editing page on PFT

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1571]
Based on conversation below, the fix here is to get the `dataset` field to render a useful field error when set to `"--------"`

***

<details>
<summary>
Saw this traceback in our logs:
</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 170, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/views/generic/preview.py", line 30, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/views/generic/preview.py", line 74, in post
    is_valid = form.is_valid()
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/forms/pages.py", line 176, in is_valid
    return super().is_valid()
  File "/usr/local/lib/python3.9/site-packages/modelcluster/forms.py", line 344, in is_valid
    formsets_are_valid = all(formset.is_valid() for formset in self.formsets.values())
  File "/usr/local/lib/python3.9/site-packages/modelcluster/forms.py", line 344, in <genexpr>
    formsets_are_valid = all(formset.is_valid() for formset in self.formsets.values())
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 321, in is_valid
    self.errors
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 304, in errors
    self.full_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/formsets.py", line 361, in full_clean
    form_errors = form.errors
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/forms.py", line 374, in full_clean
    self._post_clean()
  File "/usr/local/lib/python3.9/site-packages/django/forms/models.py", line 413, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1236, in full_clean
    self.clean()
  File "/django/common/models/pages.py", line 249, in clean
    validate_dataset_params(self.dataset, self.params)
  File "/django/statistics/validators.py", line 22, in validate_dataset_params
    fn = NUMBERS[dataset]
KeyError: ''
```

</details>

The path was `/admin/pages/4/edit/preview/`

Page with `id = 4` appears to be the Arrest category page.

[Kibana](https://logs.freedom.press/app/kibana#/discover?_g=(time:(from:now-7d,to:now))&_a=(index:'filebeat-*',query:(language:kuery,query:'_id:-UmFrIUB__PuiT3n2Sne')))

**Comment by harrislapiroff** [comment]
It seems like @stephaniesugars was the user at the time this error occurred. Not sure if it was an error that she actively witnessed or not.

**Comment by harrislapiroff** [comment]
Stephanie:

> oooooh yes, it was annoying as hell, I was going in loops trying to figure out how to change the statistics on the equipment damage page

**Comment by chigby** [comment]
It looks like this error happens when you try to save the page where a statistics item has "--------" chosen for the Dataset field.

**Comment by harrislapiroff** [comment]
Aha. Let's get that to return an informative field/form error instead!

**Comment by chigby** [comment]
Maybe even better: provide a default value so you can't even pick "------"
