### ISSUE TITLE
Requests to /authors/xxxxx throw an internal server error with traceback TemplateDoesNotExist common/person_page.html

### ISSUE THREAD

**Issue by mig5** [freedomofpress/pressfreedomtracker.us#1788]
For example

https://pressfreedomtracker.us/authors/trevor-timm

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 65, in resolve_template
    return get_template(template, using=self.using)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: common/person_page.html
```

**Comment by SaptakS** [comment]
We don't use the /author/<author_name> path in our website. Because it's a wagtail page, it's technically visitable (if that can be a word) and has a template associated with it which doesn't exist anymore. We can just add a meta redirect in that template file to redirect correctly to the `/blog/?author=<author_id>` page

**Comment by chigby** [comment]
My estimation of what's happening here is these pages are now showing up on the sitemap and so the URL is out there. The simplest thing to do is basically what @SaptakS wrote, but it is probably even easier to send the redirect at the server level, so anytime a `PersonPage` is requested we respond with a 301 code.

The more elaborate solution is: if these entities are not pages, they ought to be snippets instead, so maybe we should convert these into snippets, which would also remove them from the site map, page hierarchy, and other places they don't belong.

**Comment by SaptakS** [comment]
I do like the snippet idea given they are not actually pages.

**Comment by chigby** [comment]
It looks like the changes to Wagtail in 4.2 through 5.2 include some updates to how snippets are handled in the admin, it might make sense to save this issue until after we upgrade.

**Comment by harrislapiroff** [comment]
If we're going to hold off on it I do think we should probably add a redirect response and/or put an exclusion into our sitemap to avoid listing them. Thoughts?

**Comment by chigby** [comment]
Does the sitemap support exclusions?

Maybe the pages can be made private. I don't think that would affect how we're using them, but I can check.

**Comment by chigby** [comment]
I clicked "unpublish" on Kirsten's author page on staging:

* The author page: https://staging.pressfreedomtracker.us/authors/kirstin-mccudden/
* Filtered blog page: https://staging.pressfreedomtracker.us/blog/?author=425
* Sitemap: https://staging.pressfreedomtracker.us/sitemap.xml

**Comment by chigby** [comment]
Seems like this does work for removing pages from the sitemap and avoiding the 500 error. 

I couldn't figure out how to customize the sitemap to exclude certain pages without unpublishing them.

**Comment by SaptakS** [comment]
I mean we can override the `Sitemap` class and the `sitemap` view with our own logic of exclusion, but that might be more work than we want?

If we are adding redirects, we can leave it in the sitemap but disallow it from robots.txt so that bots ( at least the ones that follow robots.txt and sitemap) will ignore those URLs.

**Comment by harrislapiroff** [comment]
I guess unpublishing is a decent solution! I'll open a content ticket to handle that and we can save this ticket for after the Wagtail upgrade.

**Comment by harrislapiroff** [comment]
I unpublished those pages, so the temporary solution is in place. Still waiting for next wagtail upgrade for the permanent solution.

**Comment by chigby** [comment]
Unblocked by https://github.com/freedomofpress/pressfreedomtracker.us/pull/1827

**Comment by paulschreiber** [comment]
This is no longer crashing.
